### ISSUE TITLE
Request for GT2560 V4.1 rev B Schematics

### ISSUE THREAD

**Issue by dnettoRaw** [Geeetech3D/Diagram#15]

**Comment by danielneum** [comment]
Dumb, i am searching for the same Schematics.

**Comment by dnettoRaw** [comment]
hey @danielneum  

I found the documentation:  
[GT2560V4.1BSCHA20T.pdf](https://github.com/Geeetech3D/Diagram/files/8199212/GT2560V4.1BSCHA20T.pdf)

source: https://www.geeetech.com/download.html?spm=a2g0s.imconversation.0.0.22d23e5fXlQBWv&download_id=45
